---
- hosts: dbservers
  become: true
  tasks:
  - name: install mysql-server
    yum: 
      name: mysql-server
      state: latest
  - name: start it
    service:
      name: mysqld
      state: restarted
  - name: selinux dps for copy
    yum:
      name: libselinux-python
      state: latest
  - name: copy up the base database
    copy:
      src: ../configs/alldb.sql
      dest: /tmp/alldb.sql
  - name: get restore module
    yum:
      name: MySQL-python
      state: latest
  - name: restore database
    mysql_db:
      name: all
      state: import
      target: /tmp/alldb.sql
      login_user: root
      login_password: 
  - name: upload user fix script
    copy: 
      src: ../configs/addbugs.sql
      dest: /tmp/addbugs.sql
  - name: run it
    shell: /usr/bin/mysql -u root < /tmp/addbugs.sql
